Vagrant.configure("2") do |config|
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/centos7"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos"
	  vb.cpus = 4
    vb.memory = "4096"
  end
  config.vm.provision "shell", path: "./init.sh"
end