Vagrant.configure("2") do |config|
  config.vm.define "vps1" do |vps1|
    vps1.vm.box = "gusztavvargadr/windows-10"
	  vps1.vm.network "private_network", ip: "192.168.56.2"
	  vps1.vm.provider "virtualbox" do |vb|
      vb.name = "vps1"
      vb.memory = "4096"
	    vb.cpus = 4
      vb.gui = true
    end
  end
end